Created FFI for MnemonicWallet
forbole/cosmos-rust-wallet pull request #14
Opened 2021-05-04 08:10 UTC by manu0466

This PR introduces the  **FFI** (Foreign Function Interface) to expose the `crw-wallet` package functionalities to other programming languages.

2021-05-04 12:18 UTC, bragaz requested changes
looks ok to me, some small typos.

2021-05-04 14:01 UTC, manu0466 commented
@bragaz I have fixed the typos.
During the review i have also noticed that was missing a function to retrieve the public key and so I have added it.

2021-05-04 16:44 UTC, bragaz requested changes

2021-05-04 16:44 UTC, bragaz commented on packages/crw-wallet/ffi-binding.h
> + * @brief GGets secp256 public key from the wallet.
typo
```suggestion
 * @brief Gets secp256 public key from the wallet.
```

2021-05-05 05:27 UTC, RiccardoM commented on packages/crw-wallet/ffi-binding.h
> + * @brief This C header file expose the FFI defined inside the ffi crate.
```suggestion
 * @brief This C header file exposes the FFI defined inside the ffi crate.
```

2021-05-05 05:27 UTC, RiccardoM commented on packages/crw-wallet/ffi-binding.h
> + * @brief Struct that represent a signature.
```suggestion
 * @brief Struct that represents a signature.
```

2021-05-05 07:11 UTC, bragaz approved these changes

2021-05-05 07:29 UTC, merged